[catalog.gimp]
name = "GIMP"
category = "editor"

[templates.gimp]
input_path = "gimp.css"
output_path = "~/.config/GIMP/3.2/gimp.css"
requires_path = "~/.config/GIMP"

[templates.gimp-flatpak]
input_path = "gimp.css"
output_path = "~/.var/app/org.gimp.GIMP/config/GIMP/3.2/gimp.css"
requires_path = "~/.var/app/org.gimp.GIMP"
