[catalog.darktable]
name = "darktable"
category = "editor"

[templates.darktable]
input_path = "noctalia.css"
output_path = "~/.config/darktable/themes/noctalia.css"
requires_path = "~/.config/darktable"

[templates.darktable-flatpak]
input_path = "noctalia-flatpak.css"
output_path = "~/.var/app/org.darktable.Darktable/config/darktable/themes/noctalia.css"
requires_path = "~/.var/app/org.darktable.Darktable"
