[catalog.lazygit]
name = "lazygit"
category = "terminal"

[templates.lazygit]
input_path = "lazygit.yml"
output_path = "$XDG_CONFIG_HOME/lazygit/themes/noctalia.yml"
post_hook = "bash '{{ config_dir }}/apply.sh'"
