color0 #14121c
color1 #ffb4ab
color2 #92ccff
color3 #98ccf9
color4 #cbbeff
color5 #92ccff
color6 #98ccf9
color7 #e6e0ef
color8 #948da5
color9 #ffb4ab
color10 #92ccff
color11 #98ccf9
color12 #cbbeff
color13 #92ccff
color14 #98ccf9
color15 #e6e0ef

cursor                #e6e0ef
cursor_text_color     #14121c
background            #14121c
foreground            #e6e0ef
selection_foreground  #cac3dc
selection_background  #484458
active_border_color   #92ccff
inactive_border_color #484458
url_color             #92ccff

active_tab_foreground   #003351
active_tab_background   #92ccff
inactive_tab_foreground #cac3dc
inactive_tab_background #484458
cursor_trail_color      #cac3dc
