[catalog.ungoogled-chromium]
name = "Ungoogled Chromium"
category = "browser"

[templates.ungoogled_chromium_theme]
input_path = "manifest.json"
output_path = "$XDG_CACHE_HOME/noctalia/ungoogled-chromium/theme/manifest.json"
post_hook = "bash '{{ config_dir }}/apply.sh'"
