[catalog.inkscape]
name = "Inkscape"
category = "editor"

[templates.inkscape]
input_path = "user.css"
output_path = "~/.config/inkscape/ui/user.css"
requires_path = "~/.config/inkscape"

[templates.inkscape-flatpak]
input_path = "user.css"
output_path = "~/.var/app/org.inkscape.Inkscape/config/inkscape/ui/user.css"
requires_path = "~/.var/app/org.inkscape.Inkscape"
