[catalog.zed]
name = "Zed"
category = "editor"

[templates.zed]
input_path = "zed.json"
output_path = "$XDG_CONFIG_HOME/zed/themes/noctalia.json"

[templates.gram]
input_path = "zed.json"
output_path = "$XDG_CONFIG_HOME/gram/themes/noctalia.json"
