[catalog.whitesur-icons]
name = "WhiteSur Icon Theme"
category = "system"

[templates.whitesur_icons]
input_path = "colors"
output_path = "colors-final"
post_hook = "bash '{{ config_dir }}/apply.sh'"
