[catalog.yazi]
name = "Yazi"
category = "terminal"

[templates.yazi]
input_path = "yazi.toml"
output_path = "$XDG_CONFIG_HOME/yazi/flavors/noctalia.yazi/flavor.toml"
post_hook = "bash '{{ config_dir }}/apply.sh'"

[templates.yazi-syntax]
input_path = "yazi.tmTheme"
output_path = "$XDG_CONFIG_HOME/yazi/flavors/noctalia.yazi/tmtheme.xml"
